// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using uFrame.Kernel.Serialization;
    using uFrame.MVVM;
    using uFrame.MVVM.Bindings;
    using uFrame.MVVM.Services;
    using uFrame.MVVM.ViewModels;
    using UniRx;
    using UnityEngine;
    
    
    public class HealthPanelViewBase : EntityPanelView {
        
        [UnityEngine.SerializeField()]
        [uFrame.MVVM.Attributes.UFGroup("View Model Properties")]
        [UnityEngine.HideInInspector()]
        public Int32 _HP_Max;
        
        [UnityEngine.SerializeField()]
        [uFrame.MVVM.Attributes.UFGroup("View Model Properties")]
        [UnityEngine.HideInInspector()]
        public Int32 _HP;
        
        [uFrame.MVVM.Attributes.UFToggleGroup("HP")]
        [UnityEngine.HideInInspector()]
        public bool _BindHP = true;
        
        [uFrame.MVVM.Attributes.UFGroup("HP")]
        [UnityEngine.SerializeField()]
        [UnityEngine.HideInInspector()]
        [UnityEngine.Serialization.FormerlySerializedAsAttribute("_HPonlyWhenChanged")]
        protected bool _HPOnlyWhenChanged;
        
        [uFrame.MVVM.Attributes.UFToggleGroup("HP_Max")]
        [UnityEngine.HideInInspector()]
        public bool _BindHP_Max = true;
        
        [uFrame.MVVM.Attributes.UFGroup("HP_Max")]
        [UnityEngine.SerializeField()]
        [UnityEngine.HideInInspector()]
        [UnityEngine.Serialization.FormerlySerializedAsAttribute("_HP_MaxonlyWhenChanged")]
        protected bool _HP_MaxOnlyWhenChanged;
        
        public override string DefaultIdentifier {
            get {
                return base.DefaultIdentifier;
            }
        }
        
        public override System.Type ViewModelType {
            get {
                return typeof(HealthEntityViewModel);
            }
        }
        
        public HealthEntityViewModel HealthEntity {
            get {
                return (HealthEntityViewModel)ViewModelObject;
            }
        }
        
        protected override void InitializeViewModel(uFrame.MVVM.ViewModels.ViewModel model) {
            base.InitializeViewModel(model);
            // NOTE: this method is only invoked if the 'Initialize ViewModel' is checked in the inspector.
            // var vm = model as HealthEntityViewModel;
            // This method is invoked when applying the data from the inspector to the viewmodel.  Add any view-specific customizations here.
            var healthpanelview = ((HealthEntityViewModel)model);
            healthpanelview.HP_Max = this._HP_Max;
            healthpanelview.HP = this._HP;
        }
        
        public override void Bind() {
            base.Bind();
            // Use this.HealthEntity to access the viewmodel.
            // Use this method to subscribe to the view-model.
            // Any designer bindings are created in the base implementation.
            if (_BindHP) {
                this.BindProperty(this.HealthEntity.HPProperty, this.HPChanged, _HPOnlyWhenChanged);
            }
            if (_BindHP_Max) {
                this.BindProperty(this.HealthEntity.HP_MaxProperty, this.HP_MaxChanged, _HP_MaxOnlyWhenChanged);
            }
        }
        
        public virtual void HPChanged(Int32 arg1) {
        }
        
        public virtual void HP_MaxChanged(Int32 arg1) {
        }
    }
}
