// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using uFrame.Kernel.Serialization;
    using uFrame.MVVM;
    using uFrame.MVVM.Bindings;
    using uFrame.MVVM.Services;
    using uFrame.MVVM.ViewModels;
    using UniRx;
    using UnityEngine;
    
    
    public class SkillEntityViewBase : SuperPowerEntityView {
        
        [UnityEngine.SerializeField()]
        [uFrame.MVVM.Attributes.UFGroup("View Model Properties")]
        [UnityEngine.HideInInspector()]
        public Int32 _isIceFreezing;
        
        [uFrame.MVVM.Attributes.UFToggleGroup("isIceFreezing")]
        [UnityEngine.HideInInspector()]
        public bool _BindisIceFreezing = true;
        
        [uFrame.MVVM.Attributes.UFGroup("isIceFreezing")]
        [UnityEngine.SerializeField()]
        [UnityEngine.HideInInspector()]
        [UnityEngine.Serialization.FormerlySerializedAsAttribute("_isIceFreezingonlyWhenChanged")]
        protected bool _isIceFreezingOnlyWhenChanged;
        
        public override string DefaultIdentifier {
            get {
                return base.DefaultIdentifier;
            }
        }
        
        public override System.Type ViewModelType {
            get {
                return typeof(SkillEntityViewModel);
            }
        }
        
        public SkillEntityViewModel SkillEntity {
            get {
                return (SkillEntityViewModel)ViewModelObject;
            }
        }
        
        protected override void InitializeViewModel(uFrame.MVVM.ViewModels.ViewModel model) {
            base.InitializeViewModel(model);
            // NOTE: this method is only invoked if the 'Initialize ViewModel' is checked in the inspector.
            // var vm = model as SkillEntityViewModel;
            // This method is invoked when applying the data from the inspector to the viewmodel.  Add any view-specific customizations here.
            var skillentityview = ((SkillEntityViewModel)model);
            skillentityview.isIceFreezing = this._isIceFreezing;
        }
        
        public override void Bind() {
            base.Bind();
            // Use this.SkillEntity to access the viewmodel.
            // Use this method to subscribe to the view-model.
            // Any designer bindings are created in the base implementation.
            if (_BindisIceFreezing) {
                this.BindProperty(this.SkillEntity.isIceFreezingProperty, this.isIceFreezingChanged, _isIceFreezingOnlyWhenChanged);
            }
        }
        
        public virtual void isIceFreezingChanged(Int32 arg1) {
        }
    }
}
