// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using uFrame.Kernel.Serialization;
    using uFrame.MVVM;
    using uFrame.MVVM.Bindings;
    using uFrame.MVVM.Services;
    using uFrame.MVVM.ViewModels;
    using UniRx;
    using UnityEngine;
    
    
    public class SuperPowerRingViewBase : HealthRingView {
        
        [UnityEngine.SerializeField()]
        [uFrame.MVVM.Attributes.UFGroup("View Model Properties")]
        [UnityEngine.HideInInspector()]
        public Int32 _MSP;
        
        [UnityEngine.SerializeField()]
        [uFrame.MVVM.Attributes.UFGroup("View Model Properties")]
        [UnityEngine.HideInInspector()]
        public Int32 _MSP_Max;
        
        [UnityEngine.SerializeField()]
        [uFrame.MVVM.Attributes.UFGroup("View Model Properties")]
        [UnityEngine.HideInInspector()]
        public Int32 _SP_Max;
        
        [UnityEngine.SerializeField()]
        [uFrame.MVVM.Attributes.UFGroup("View Model Properties")]
        [UnityEngine.HideInInspector()]
        public Int32 _SP;
        
        [uFrame.MVVM.Attributes.UFToggleGroup("SP")]
        [UnityEngine.HideInInspector()]
        public bool _BindSP = true;
        
        [uFrame.MVVM.Attributes.UFGroup("SP")]
        [UnityEngine.SerializeField()]
        [UnityEngine.HideInInspector()]
        [UnityEngine.Serialization.FormerlySerializedAsAttribute("_SPonlyWhenChanged")]
        protected bool _SPOnlyWhenChanged;
        
        [uFrame.MVVM.Attributes.UFToggleGroup("MSP_Max")]
        [UnityEngine.HideInInspector()]
        public bool _BindMSP_Max = true;
        
        [uFrame.MVVM.Attributes.UFGroup("MSP_Max")]
        [UnityEngine.SerializeField()]
        [UnityEngine.HideInInspector()]
        [UnityEngine.Serialization.FormerlySerializedAsAttribute("_MSP_MaxonlyWhenChanged")]
        protected bool _MSP_MaxOnlyWhenChanged;
        
        [uFrame.MVVM.Attributes.UFToggleGroup("SP_Max")]
        [UnityEngine.HideInInspector()]
        public bool _BindSP_Max = true;
        
        [uFrame.MVVM.Attributes.UFGroup("SP_Max")]
        [UnityEngine.SerializeField()]
        [UnityEngine.HideInInspector()]
        [UnityEngine.Serialization.FormerlySerializedAsAttribute("_SP_MaxonlyWhenChanged")]
        protected bool _SP_MaxOnlyWhenChanged;
        
        [uFrame.MVVM.Attributes.UFToggleGroup("MSP")]
        [UnityEngine.HideInInspector()]
        public bool _BindMSP = true;
        
        [uFrame.MVVM.Attributes.UFGroup("MSP")]
        [UnityEngine.SerializeField()]
        [UnityEngine.HideInInspector()]
        [UnityEngine.Serialization.FormerlySerializedAsAttribute("_MSPonlyWhenChanged")]
        protected bool _MSPOnlyWhenChanged;
        
        public override string DefaultIdentifier {
            get {
                return base.DefaultIdentifier;
            }
        }
        
        public override System.Type ViewModelType {
            get {
                return typeof(SuperPowerEntityViewModel);
            }
        }
        
        public SuperPowerEntityViewModel SuperPowerEntity {
            get {
                return (SuperPowerEntityViewModel)ViewModelObject;
            }
        }
        
        protected override void InitializeViewModel(uFrame.MVVM.ViewModels.ViewModel model) {
            base.InitializeViewModel(model);
            // NOTE: this method is only invoked if the 'Initialize ViewModel' is checked in the inspector.
            // var vm = model as SuperPowerEntityViewModel;
            // This method is invoked when applying the data from the inspector to the viewmodel.  Add any view-specific customizations here.
            var superpowerringview = ((SuperPowerEntityViewModel)model);
            superpowerringview.MSP = this._MSP;
            superpowerringview.MSP_Max = this._MSP_Max;
            superpowerringview.SP_Max = this._SP_Max;
            superpowerringview.SP = this._SP;
        }
        
        public override void Bind() {
            base.Bind();
            // Use this.SuperPowerEntity to access the viewmodel.
            // Use this method to subscribe to the view-model.
            // Any designer bindings are created in the base implementation.
            if (_BindSP) {
                this.BindProperty(this.SuperPowerEntity.SPProperty, this.SPChanged, _SPOnlyWhenChanged);
            }
            if (_BindMSP_Max) {
                this.BindProperty(this.SuperPowerEntity.MSP_MaxProperty, this.MSP_MaxChanged, _MSP_MaxOnlyWhenChanged);
            }
            if (_BindSP_Max) {
                this.BindProperty(this.SuperPowerEntity.SP_MaxProperty, this.SP_MaxChanged, _SP_MaxOnlyWhenChanged);
            }
            if (_BindMSP) {
                this.BindProperty(this.SuperPowerEntity.MSPProperty, this.MSPChanged, _MSPOnlyWhenChanged);
            }
        }
        
        public virtual void SPChanged(Int32 arg1) {
        }
        
        public virtual void MSP_MaxChanged(Int32 arg1) {
        }
        
        public virtual void SP_MaxChanged(Int32 arg1) {
        }
        
        public virtual void MSPChanged(Int32 arg1) {
        }
    }
}
