// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class ArenaControllerBase : EntityCommonController {
        
        private uFrame.MVVM.ViewModels.IViewModelManager<ArenaViewModel> _ArenaViewModelManager;
        
        [uFrame.IOC.InjectAttribute("Arena")]
        public uFrame.MVVM.ViewModels.IViewModelManager<ArenaViewModel> ArenaViewModelManager {
            get {
                return _ArenaViewModelManager;
            }
            set {
                _ArenaViewModelManager = value;
            }
        }
        
        public IEnumerable<ArenaViewModel> ArenaViewModels {
            get {
                return ArenaViewModelManager.ViewModels;
            }
        }
        
        public override void Setup() {
            base.Setup();
            // This is called when the controller is created
        }
        
        public override void Initialize(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.Initialize(viewModel);
            // This is called when a viewmodel is created
            this.InitializeArena(((ArenaViewModel)(viewModel)));
        }
        
        public virtual ArenaViewModel CreateArena() {
            return ((ArenaViewModel)(this.Create(Guid.NewGuid().ToString())));
        }
        
        public override uFrame.MVVM.ViewModels.ViewModel CreateEmpty() {
            return new ArenaViewModel(this.EventAggregator);
        }
        
        public virtual void InitializeArena(ArenaViewModel viewModel) {
            // This is called when a ArenaViewModel is created
            ArenaViewModelManager.Add(viewModel);
        }
        
        public override void DisposingViewModel(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.DisposingViewModel(viewModel);
            ArenaViewModelManager.Remove(viewModel);
        }
    }
}
