// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class CampEntityControllerBase : SkillEntityController {
        
        private uFrame.MVVM.ViewModels.IViewModelManager<CampEntityViewModel> _CampEntityViewModelManager;
        
        [uFrame.IOC.InjectAttribute("CampEntity")]
        public uFrame.MVVM.ViewModels.IViewModelManager<CampEntityViewModel> CampEntityViewModelManager {
            get {
                return _CampEntityViewModelManager;
            }
            set {
                _CampEntityViewModelManager = value;
            }
        }
        
        public IEnumerable<CampEntityViewModel> CampEntityViewModels {
            get {
                return CampEntityViewModelManager.ViewModels;
            }
        }
        
        public override void Setup() {
            base.Setup();
            // This is called when the controller is created
        }
        
        public override void Initialize(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.Initialize(viewModel);
            // This is called when a viewmodel is created
            this.InitializeCampEntity(((CampEntityViewModel)(viewModel)));
        }
        
        public virtual CampEntityViewModel CreateCampEntity() {
            return ((CampEntityViewModel)(this.Create(Guid.NewGuid().ToString())));
        }
        
        public override uFrame.MVVM.ViewModels.ViewModel CreateEmpty() {
            return new CampEntityViewModel(this.EventAggregator);
        }
        
        public virtual void InitializeCampEntity(CampEntityViewModel viewModel) {
            // This is called when a CampEntityViewModel is created
            CampEntityViewModelManager.Add(viewModel);
        }
        
        public override void DisposingViewModel(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.DisposingViewModel(viewModel);
            CampEntityViewModelManager.Remove(viewModel);
        }
    }
}
