// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using MagicFire.HuanHuoUFrame;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class EntityCommonControllerBase : uFrame.MVVM.Controller {
        
        private uFrame.MVVM.ViewModels.IViewModelManager<EntityCommonViewModel> _EntityCommonViewModelManager;
        
        [uFrame.IOC.InjectAttribute("EntityCommon")]
        public uFrame.MVVM.ViewModels.IViewModelManager<EntityCommonViewModel> EntityCommonViewModelManager {
            get {
                return _EntityCommonViewModelManager;
            }
            set {
                _EntityCommonViewModelManager = value;
            }
        }
        
        public IEnumerable<EntityCommonViewModel> EntityCommonViewModels {
            get {
                return EntityCommonViewModelManager.ViewModels;
            }
        }
        
        public override void Setup() {
            base.Setup();
            // This is called when the controller is created
        }
        
        public override void Initialize(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.Initialize(viewModel);
            // This is called when a viewmodel is created
            this.InitializeEntityCommon(((EntityCommonViewModel)(viewModel)));
        }
        
        public virtual EntityCommonViewModel CreateEntityCommon() {
            return ((EntityCommonViewModel)(this.Create(Guid.NewGuid().ToString())));
        }
        
        public override uFrame.MVVM.ViewModels.ViewModel CreateEmpty() {
            return new EntityCommonViewModel(this.EventAggregator);
        }
        
        public virtual void InitializeEntityCommon(EntityCommonViewModel viewModel) {
            // This is called when a EntityCommonViewModel is created
            viewModel.OnDestroy.Action = this.OnDestroyHandler;
            viewModel.OnLeaveWorld.Action = this.OnLeaveWorldHandler;
            EntityCommonViewModelManager.Add(viewModel);
        }
        
        public override void DisposingViewModel(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.DisposingViewModel(viewModel);
            EntityCommonViewModelManager.Remove(viewModel);
        }
        
        public virtual void OnDestroyHandler(OnDestroyCommand command) {
            this.OnDestroy(command.Sender as EntityCommonViewModel, command);
        }
        
        public virtual void OnLeaveWorldHandler(OnLeaveWorldCommand command) {
            this.OnLeaveWorld(command.Sender as EntityCommonViewModel, command);
        }
        
        public virtual void OnDestroy(EntityCommonViewModel viewModel, OnDestroyCommand arg) {
        }
        
        public virtual void OnLeaveWorld(EntityCommonViewModel viewModel, OnLeaveWorldCommand arg) {
        }
    }
}
