// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using MagicFire.HuanHuoUFrame;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class GongFaEntityControllerBase : MotionSystemController {
        
        private uFrame.MVVM.ViewModels.IViewModelManager<GongFaEntityViewModel> _GongFaEntityViewModelManager;
        
        [uFrame.IOC.InjectAttribute("GongFaEntity")]
        public uFrame.MVVM.ViewModels.IViewModelManager<GongFaEntityViewModel> GongFaEntityViewModelManager {
            get {
                return _GongFaEntityViewModelManager;
            }
            set {
                _GongFaEntityViewModelManager = value;
            }
        }
        
        public IEnumerable<GongFaEntityViewModel> GongFaEntityViewModels {
            get {
                return GongFaEntityViewModelManager.ViewModels;
            }
        }
        
        public override void Setup() {
            base.Setup();
            // This is called when the controller is created
        }
        
        public override void Initialize(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.Initialize(viewModel);
            // This is called when a viewmodel is created
            this.InitializeGongFaEntity(((GongFaEntityViewModel)(viewModel)));
        }
        
        public virtual GongFaEntityViewModel CreateGongFaEntity() {
            return ((GongFaEntityViewModel)(this.Create(Guid.NewGuid().ToString())));
        }
        
        public override uFrame.MVVM.ViewModels.ViewModel CreateEmpty() {
            return new GongFaEntityViewModel(this.EventAggregator);
        }
        
        public virtual void InitializeGongFaEntity(GongFaEntityViewModel viewModel) {
            // This is called when a GongFaEntityViewModel is created
            viewModel.learnGongFa.Action = this.learnGongFaHandler;
            GongFaEntityViewModelManager.Add(viewModel);
        }
        
        public override void DisposingViewModel(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.DisposingViewModel(viewModel);
            GongFaEntityViewModelManager.Remove(viewModel);
        }
        
        public virtual void learnGongFaHandler(learnGongFaCommand command) {
            this.learnGongFa(command.Sender as GongFaEntityViewModel, command);
        }
        
        public virtual void learnGongFa(GongFaEntityViewModel viewModel, learnGongFaCommand arg) {
        }
    }
}
