// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class MagicWeaponSystemControllerBase : SkillEntityController {
        
        private uFrame.MVVM.ViewModels.IViewModelManager<MagicWeaponSystemViewModel> _MagicWeaponSystemViewModelManager;
        
        [uFrame.IOC.InjectAttribute("MagicWeaponSystem")]
        public uFrame.MVVM.ViewModels.IViewModelManager<MagicWeaponSystemViewModel> MagicWeaponSystemViewModelManager {
            get {
                return _MagicWeaponSystemViewModelManager;
            }
            set {
                _MagicWeaponSystemViewModelManager = value;
            }
        }
        
        public IEnumerable<MagicWeaponSystemViewModel> MagicWeaponSystemViewModels {
            get {
                return MagicWeaponSystemViewModelManager.ViewModels;
            }
        }
        
        public override void Setup() {
            base.Setup();
            // This is called when the controller is created
        }
        
        public override void Initialize(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.Initialize(viewModel);
            // This is called when a viewmodel is created
            this.InitializeMagicWeaponSystem(((MagicWeaponSystemViewModel)(viewModel)));
        }
        
        public virtual MagicWeaponSystemViewModel CreateMagicWeaponSystem() {
            return ((MagicWeaponSystemViewModel)(this.Create(Guid.NewGuid().ToString())));
        }
        
        public override uFrame.MVVM.ViewModels.ViewModel CreateEmpty() {
            return new MagicWeaponSystemViewModel(this.EventAggregator);
        }
        
        public virtual void InitializeMagicWeaponSystem(MagicWeaponSystemViewModel viewModel) {
            // This is called when a MagicWeaponSystemViewModel is created
            MagicWeaponSystemViewModelManager.Add(viewModel);
        }
        
        public override void DisposingViewModel(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.DisposingViewModel(viewModel);
            MagicWeaponSystemViewModelManager.Remove(viewModel);
        }
    }
}
