// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using MagicFire.HuanHuoUFrame;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class MonsterControllerBase : SuperPowerEntityController {
        
        private uFrame.MVVM.ViewModels.IViewModelManager<MonsterViewModel> _MonsterViewModelManager;
        
        [uFrame.IOC.InjectAttribute("Monster")]
        public uFrame.MVVM.ViewModels.IViewModelManager<MonsterViewModel> MonsterViewModelManager {
            get {
                return _MonsterViewModelManager;
            }
            set {
                _MonsterViewModelManager = value;
            }
        }
        
        public IEnumerable<MonsterViewModel> MonsterViewModels {
            get {
                return MonsterViewModelManager.ViewModels;
            }
        }
        
        public override void Setup() {
            base.Setup();
            // This is called when the controller is created
        }
        
        public override void Initialize(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.Initialize(viewModel);
            // This is called when a viewmodel is created
            this.InitializeMonster(((MonsterViewModel)(viewModel)));
        }
        
        public virtual MonsterViewModel CreateMonster() {
            return ((MonsterViewModel)(this.Create(Guid.NewGuid().ToString())));
        }
        
        public override uFrame.MVVM.ViewModels.ViewModel CreateEmpty() {
            return new MonsterViewModel(this.EventAggregator);
        }
        
        public virtual void InitializeMonster(MonsterViewModel viewModel) {
            // This is called when a MonsterViewModel is created
            viewModel.StartMove.Action = this.StartMoveHandler;
            viewModel.StopMove.Action = this.StopMoveHandler;
            MonsterViewModelManager.Add(viewModel);
        }
        
        public override void DisposingViewModel(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.DisposingViewModel(viewModel);
            MonsterViewModelManager.Remove(viewModel);
        }
        
        public virtual void StartMoveHandler(StartMoveCommand command) {
            this.StartMove(command.Sender as MonsterViewModel, command);
        }
        
        public virtual void StopMoveHandler(StopMoveCommand command) {
            this.StopMove(command.Sender as MonsterViewModel, command);
        }
        
        public virtual void StartMove(MonsterViewModel viewModel, StartMoveCommand arg) {
        }
        
        public virtual void StopMove(MonsterViewModel viewModel, StopMoveCommand arg) {
        }
    }
}
