// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using MagicFire.HuanHuoUFrame;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class MotionSystemControllerBase : SuperPowerEntityController {
        
        private uFrame.MVVM.ViewModels.IViewModelManager<MotionSystemViewModel> _MotionSystemViewModelManager;
        
        [uFrame.IOC.InjectAttribute("MotionSystem")]
        public uFrame.MVVM.ViewModels.IViewModelManager<MotionSystemViewModel> MotionSystemViewModelManager {
            get {
                return _MotionSystemViewModelManager;
            }
            set {
                _MotionSystemViewModelManager = value;
            }
        }
        
        public IEnumerable<MotionSystemViewModel> MotionSystemViewModels {
            get {
                return MotionSystemViewModelManager.ViewModels;
            }
        }
        
        public override void Setup() {
            base.Setup();
            // This is called when the controller is created
        }
        
        public override void Initialize(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.Initialize(viewModel);
            // This is called when a viewmodel is created
            this.InitializeMotionSystem(((MotionSystemViewModel)(viewModel)));
        }
        
        public virtual MotionSystemViewModel CreateMotionSystem() {
            return ((MotionSystemViewModel)(this.Create(Guid.NewGuid().ToString())));
        }
        
        public override uFrame.MVVM.ViewModels.ViewModel CreateEmpty() {
            return new MotionSystemViewModel(this.EventAggregator);
        }
        
        public virtual void InitializeMotionSystem(MotionSystemViewModel viewModel) {
            // This is called when a MotionSystemViewModel is created
            viewModel.RequestStopMove.Action = this.RequestStopMoveHandler;
            viewModel.OnStopMove.Action = this.OnStopMoveHandler;
            viewModel.DoMove.Action = this.DoMoveHandler;
            viewModel.RequestMove.Action = this.RequestMoveHandler;
            MotionSystemViewModelManager.Add(viewModel);
        }
        
        public override void DisposingViewModel(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.DisposingViewModel(viewModel);
            MotionSystemViewModelManager.Remove(viewModel);
        }
        
        public virtual void RequestStopMoveHandler(RequestStopMoveCommand command) {
            this.RequestStopMove(command.Sender as MotionSystemViewModel, command);
        }
        
        public virtual void OnStopMoveHandler(OnStopMoveCommand command) {
            this.OnStopMove(command.Sender as MotionSystemViewModel, command);
        }
        
        public virtual void DoMoveHandler(DoMoveCommand command) {
            this.DoMove(command.Sender as MotionSystemViewModel, command);
        }
        
        public virtual void RequestMoveHandler(RequestMoveCommand command) {
            this.RequestMove(command.Sender as MotionSystemViewModel, command);
        }
        
        public virtual void RequestStopMove(MotionSystemViewModel viewModel, RequestStopMoveCommand arg) {
        }
        
        public virtual void OnStopMove(MotionSystemViewModel viewModel, OnStopMoveCommand arg) {
        }
        
        public virtual void DoMove(MotionSystemViewModel viewModel, DoMoveCommand arg) {
        }
        
        public virtual void RequestMove(MotionSystemViewModel viewModel, RequestMoveCommand arg) {
        }
    }
}
