// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using MagicFire.HuanHuoUFrame;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class PropSystemControllerBase : ArenaSystemController {
        
        private uFrame.MVVM.ViewModels.IViewModelManager<PropSystemViewModel> _PropSystemViewModelManager;
        
        [uFrame.IOC.InjectAttribute("PropSystem")]
        public uFrame.MVVM.ViewModels.IViewModelManager<PropSystemViewModel> PropSystemViewModelManager {
            get {
                return _PropSystemViewModelManager;
            }
            set {
                _PropSystemViewModelManager = value;
            }
        }
        
        public IEnumerable<PropSystemViewModel> PropSystemViewModels {
            get {
                return PropSystemViewModelManager.ViewModels;
            }
        }
        
        public override void Setup() {
            base.Setup();
            // This is called when the controller is created
        }
        
        public override void Initialize(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.Initialize(viewModel);
            // This is called when a viewmodel is created
            this.InitializePropSystem(((PropSystemViewModel)(viewModel)));
        }
        
        public virtual PropSystemViewModel CreatePropSystem() {
            return ((PropSystemViewModel)(this.Create(Guid.NewGuid().ToString())));
        }
        
        public override uFrame.MVVM.ViewModels.ViewModel CreateEmpty() {
            return new PropSystemViewModel(this.EventAggregator);
        }
        
        public virtual void InitializePropSystem(PropSystemViewModel viewModel) {
            // This is called when a PropSystemViewModel is created
            viewModel.OnPullStorePropListReturn.Action = this.OnPullStorePropListReturnHandler;
            viewModel.RequestPullStorePropList.Action = this.RequestPullStorePropListHandler;
            PropSystemViewModelManager.Add(viewModel);
        }
        
        public override void DisposingViewModel(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.DisposingViewModel(viewModel);
            PropSystemViewModelManager.Remove(viewModel);
        }
        
        public virtual void OnPullStorePropListReturnHandler(OnPullStorePropListReturnCommand command) {
            this.OnPullStorePropListReturn(command.Sender as PropSystemViewModel, command);
        }
        
        public virtual void RequestPullStorePropListHandler(RequestPullStorePropListCommand command) {
            this.RequestPullStorePropList(command.Sender as PropSystemViewModel, command);
        }
        
        public virtual void OnPullStorePropListReturn(PropSystemViewModel viewModel, OnPullStorePropListReturnCommand arg) {
        }
        
        public virtual void RequestPullStorePropList(PropSystemViewModel viewModel, RequestPullStorePropListCommand arg) {
        }
    }
}
