// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class SpacesManagerControllerBase : EntityCommonController {
        
        private uFrame.MVVM.ViewModels.IViewModelManager<SpacesManagerViewModel> _SpacesManagerViewModelManager;
        
        [uFrame.IOC.InjectAttribute("SpacesManager")]
        public uFrame.MVVM.ViewModels.IViewModelManager<SpacesManagerViewModel> SpacesManagerViewModelManager {
            get {
                return _SpacesManagerViewModelManager;
            }
            set {
                _SpacesManagerViewModelManager = value;
            }
        }
        
        public IEnumerable<SpacesManagerViewModel> SpacesManagerViewModels {
            get {
                return SpacesManagerViewModelManager.ViewModels;
            }
        }
        
        public override void Setup() {
            base.Setup();
            // This is called when the controller is created
        }
        
        public override void Initialize(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.Initialize(viewModel);
            // This is called when a viewmodel is created
            this.InitializeSpacesManager(((SpacesManagerViewModel)(viewModel)));
        }
        
        public virtual SpacesManagerViewModel CreateSpacesManager() {
            return ((SpacesManagerViewModel)(this.Create(Guid.NewGuid().ToString())));
        }
        
        public override uFrame.MVVM.ViewModels.ViewModel CreateEmpty() {
            return new SpacesManagerViewModel(this.EventAggregator);
        }
        
        public virtual void InitializeSpacesManager(SpacesManagerViewModel viewModel) {
            // This is called when a SpacesManagerViewModel is created
            SpacesManagerViewModelManager.Add(viewModel);
        }
        
        public override void DisposingViewModel(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.DisposingViewModel(viewModel);
            SpacesManagerViewModelManager.Remove(viewModel);
        }
    }
}
