// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class SpaceControllerBase : EntityCommonController {
        
        private uFrame.MVVM.ViewModels.IViewModelManager<SpaceViewModel> _SpaceViewModelManager;
        
        [uFrame.IOC.InjectAttribute("Space")]
        public uFrame.MVVM.ViewModels.IViewModelManager<SpaceViewModel> SpaceViewModelManager {
            get {
                return _SpaceViewModelManager;
            }
            set {
                _SpaceViewModelManager = value;
            }
        }
        
        public IEnumerable<SpaceViewModel> SpaceViewModels {
            get {
                return SpaceViewModelManager.ViewModels;
            }
        }
        
        public override void Setup() {
            base.Setup();
            // This is called when the controller is created
        }
        
        public override void Initialize(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.Initialize(viewModel);
            // This is called when a viewmodel is created
            this.InitializeSpace(((SpaceViewModel)(viewModel)));
        }
        
        public virtual SpaceViewModel CreateSpace() {
            return ((SpaceViewModel)(this.Create(Guid.NewGuid().ToString())));
        }
        
        public override uFrame.MVVM.ViewModels.ViewModel CreateEmpty() {
            return new SpaceViewModel(this.EventAggregator);
        }
        
        public virtual void InitializeSpace(SpaceViewModel viewModel) {
            // This is called when a SpaceViewModel is created
            SpaceViewModelManager.Add(viewModel);
        }
        
        public override void DisposingViewModel(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.DisposingViewModel(viewModel);
            SpaceViewModelManager.Remove(viewModel);
        }
    }
}
