// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoMVVM {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using uFrame.Kernel.Serialization;
    using uFrame.MVVM;
    using uFrame.MVVM.Bindings;
    using uFrame.MVVM.Services;
    using uFrame.MVVM.ViewModels;
    using UniRx;
    using UnityEngine;
    
    
    public class EntityCommonViewBase : uFrame.MVVM.Views.ViewBase {
        
        [UnityEngine.SerializeField()]
        [uFrame.MVVM.Attributes.UFGroup("View Model Properties")]
        [UnityEngine.HideInInspector()]
        public String _modelType;
        
        [UnityEngine.SerializeField()]
        [uFrame.MVVM.Attributes.UFGroup("View Model Properties")]
        [UnityEngine.HideInInspector()]
        public String _entityName;
        
        [UnityEngine.SerializeField()]
        [uFrame.MVVM.Attributes.UFGroup("View Model Properties")]
        [UnityEngine.HideInInspector()]
        public String _modelName;
        
        [uFrame.MVVM.Attributes.UFToggleGroup("entityName")]
        [UnityEngine.HideInInspector()]
        public bool _BindentityName = true;
        
        [uFrame.MVVM.Attributes.UFGroup("entityName")]
        [UnityEngine.SerializeField()]
        [UnityEngine.HideInInspector()]
        [UnityEngine.Serialization.FormerlySerializedAsAttribute("_entityNameonlyWhenChanged")]
        protected bool _entityNameOnlyWhenChanged;
        
        [uFrame.MVVM.Attributes.UFToggleGroup("modelType")]
        [UnityEngine.HideInInspector()]
        public bool _BindmodelType = true;
        
        [uFrame.MVVM.Attributes.UFGroup("modelType")]
        [UnityEngine.SerializeField()]
        [UnityEngine.HideInInspector()]
        [UnityEngine.Serialization.FormerlySerializedAsAttribute("_modelTypeonlyWhenChanged")]
        protected bool _modelTypeOnlyWhenChanged;
        
        [uFrame.MVVM.Attributes.UFToggleGroup("modelName")]
        [UnityEngine.HideInInspector()]
        public bool _BindmodelName = true;
        
        [uFrame.MVVM.Attributes.UFGroup("modelName")]
        [UnityEngine.SerializeField()]
        [UnityEngine.HideInInspector()]
        [UnityEngine.Serialization.FormerlySerializedAsAttribute("_modelNameonlyWhenChanged")]
        protected bool _modelNameOnlyWhenChanged;
        
        public override string DefaultIdentifier {
            get {
                return base.DefaultIdentifier;
            }
        }
        
        public override System.Type ViewModelType {
            get {
                return typeof(EntityCommonViewModel);
            }
        }
        
        public EntityCommonViewModel EntityCommon {
            get {
                return (EntityCommonViewModel)ViewModelObject;
            }
        }
        
        protected override void InitializeViewModel(uFrame.MVVM.ViewModels.ViewModel model) {
            base.InitializeViewModel(model);
            // NOTE: this method is only invoked if the 'Initialize ViewModel' is checked in the inspector.
            // var vm = model as EntityCommonViewModel;
            // This method is invoked when applying the data from the inspector to the viewmodel.  Add any view-specific customizations here.
            var entitycommonview = ((EntityCommonViewModel)model);
            entitycommonview.modelType = this._modelType;
            entitycommonview.entityName = this._entityName;
            entitycommonview.modelName = this._modelName;
        }
        
        public override void Bind() {
            base.Bind();
            // Use this.EntityCommon to access the viewmodel.
            // Use this method to subscribe to the view-model.
            // Any designer bindings are created in the base implementation.
            if (_BindentityName) {
                this.BindProperty(this.EntityCommon.entityNameProperty, this.entityNameChanged, _entityNameOnlyWhenChanged);
            }
            if (_BindmodelType) {
                this.BindProperty(this.EntityCommon.modelTypeProperty, this.modelTypeChanged, _modelTypeOnlyWhenChanged);
            }
            if (_BindmodelName) {
                this.BindProperty(this.EntityCommon.modelNameProperty, this.modelNameChanged, _modelNameOnlyWhenChanged);
            }
        }
        
        public virtual void entityNameChanged(String arg1) {
        }
        
        public virtual void modelTypeChanged(String arg1) {
        }
        
        public virtual void modelNameChanged(String arg1) {
        }
    }
}
