// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoMVVM {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class TriggerControllerBase : EntityCommonController {
        
        private uFrame.MVVM.ViewModels.IViewModelManager<TriggerViewModel> _TriggerViewModelManager;
        
        [uFrame.IOC.InjectAttribute("Trigger")]
        public uFrame.MVVM.ViewModels.IViewModelManager<TriggerViewModel> TriggerViewModelManager {
            get {
                return _TriggerViewModelManager;
            }
            set {
                _TriggerViewModelManager = value;
            }
        }
        
        public IEnumerable<TriggerViewModel> TriggerViewModels {
            get {
                return TriggerViewModelManager.ViewModels;
            }
        }
        
        public override void Setup() {
            base.Setup();
            // This is called when the controller is created
        }
        
        public override void Initialize(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.Initialize(viewModel);
            // This is called when a viewmodel is created
            this.InitializeTrigger(((TriggerViewModel)(viewModel)));
        }
        
        public virtual TriggerViewModel CreateTrigger() {
            return ((TriggerViewModel)(this.Create(Guid.NewGuid().ToString())));
        }
        
        public override uFrame.MVVM.ViewModels.ViewModel CreateEmpty() {
            return new TriggerViewModel(this.EventAggregator);
        }
        
        public virtual void InitializeTrigger(TriggerViewModel viewModel) {
            // This is called when a TriggerViewModel is created
            TriggerViewModelManager.Add(viewModel);
        }
        
        public override void DisposingViewModel(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.DisposingViewModel(viewModel);
            TriggerViewModelManager.Remove(viewModel);
        }
    }
}
