// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using MagicFire.HuanHuoUFrame;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.IOC;
    using uFrame.Kernel;
    using uFrame.Kernel.Serialization;
    using uFrame.MVVM;
    using uFrame.MVVM.Bindings;
    using uFrame.MVVM.ViewModels;
    using UniRx;
    using UnityEngine;
    
    
    public partial class ArenaSystemViewModelBase : CampEntityViewModel {
        
        private Signal<RequestEnterArenaCommand> _RequestEnterArena;
        
        public ArenaSystemViewModelBase(uFrame.Kernel.IEventAggregator aggregator) : 
                base(aggregator) {
        }
        
        public virtual Signal<RequestEnterArenaCommand> RequestEnterArena {
            get {
                return _RequestEnterArena;
            }
            set {
                _RequestEnterArena = value;
            }
        }
        
        public override void Bind() {
            base.Bind();
            this.RequestEnterArena = new Signal<RequestEnterArenaCommand>(this);
        }
        
        public virtual void Execute(RequestEnterArenaCommand argument) {
            this.RequestEnterArena.OnNext(argument);
        }
        
        public virtual void RequestEnterArena_(Int32 ArenaID) {
            var cmd = new RequestEnterArenaCommand();
            cmd.ArenaID = ArenaID;
            this.RequestEnterArena.OnNext(cmd);
        }
        
        public override void Read(uFrame.Kernel.Serialization.ISerializerStream stream) {
            base.Read(stream);
        }
        
        public override void Write(uFrame.Kernel.Serialization.ISerializerStream stream) {
            base.Write(stream);
        }
        
        protected override void FillCommands(System.Collections.Generic.List<uFrame.MVVM.ViewModels.ViewModelCommandInfo> list) {
            base.FillCommands(list);
            list.Add(new ViewModelCommandInfo("RequestEnterArena", RequestEnterArena) { ParameterType = typeof(RequestEnterArenaCommand) });
        }
        
        protected override void FillProperties(System.Collections.Generic.List<uFrame.MVVM.ViewModels.ViewModelPropertyInfo> list) {
            base.FillProperties(list);
        }
    }
    
    public partial class ArenaSystemViewModel {
        
        public ArenaSystemViewModel(uFrame.Kernel.IEventAggregator aggregator) : 
                base(aggregator) {
        }
    }
}
