// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using MagicFire.HuanHuoUFrame;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.IOC;
    using uFrame.Kernel;
    using uFrame.Kernel.Serialization;
    using uFrame.MVVM;
    using uFrame.MVVM.Bindings;
    using uFrame.MVVM.ViewModels;
    using UniRx;
    using UnityEngine;
    
    
    public partial class GongFaEntityViewModelBase : SuperPowerEntityViewModel {
        
        private P<System.Object> _gongFaListProperty;
        
        private Signal<learnGongFaCommand> _learnGongFa;
        
        public GongFaEntityViewModelBase(uFrame.Kernel.IEventAggregator aggregator) : 
                base(aggregator) {
        }
        
        public virtual P<System.Object> gongFaListProperty {
            get {
                return _gongFaListProperty;
            }
            set {
                _gongFaListProperty = value;
            }
        }
        
        public virtual object gongFaList {
            get {
                return gongFaListProperty.Value;
            }
            set {
                gongFaListProperty.Value = value;
            }
        }
        
        public virtual Signal<learnGongFaCommand> learnGongFa {
            get {
                return _learnGongFa;
            }
            set {
                _learnGongFa = value;
            }
        }
        
        public override void Bind() {
            base.Bind();
            this.learnGongFa = new Signal<learnGongFaCommand>(this);
            _gongFaListProperty = new P<System.Object>(this, "gongFaList");
        }
        
        public virtual void Execute(learnGongFaCommand argument) {
            this.learnGongFa.OnNext(argument);
        }
        
        public virtual void learnGongFa_(String gongFaName) {
            var cmd = new learnGongFaCommand();
            cmd.gongFaName = gongFaName;
            this.learnGongFa.OnNext(cmd);
        }
        
        public override void Read(uFrame.Kernel.Serialization.ISerializerStream stream) {
            base.Read(stream);
        }
        
        public override void Write(uFrame.Kernel.Serialization.ISerializerStream stream) {
            base.Write(stream);
        }
        
        protected override void FillCommands(System.Collections.Generic.List<uFrame.MVVM.ViewModels.ViewModelCommandInfo> list) {
            base.FillCommands(list);
            list.Add(new ViewModelCommandInfo("learnGongFa", learnGongFa) { ParameterType = typeof(learnGongFaCommand) });
        }
        
        protected override void FillProperties(System.Collections.Generic.List<uFrame.MVVM.ViewModels.ViewModelPropertyInfo> list) {
            base.FillProperties(list);
            // PropertiesChildItem
            list.Add(new ViewModelPropertyInfo(_gongFaListProperty, false, false, false, false));
        }
    }
    
    public partial class GongFaEntityViewModel {
        
        public GongFaEntityViewModel(uFrame.Kernel.IEventAggregator aggregator) : 
                base(aggregator) {
        }
    }
}
