// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using MagicFire.HuanHuoUFrame;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.IOC;
    using uFrame.Kernel;
    using uFrame.Kernel.Serialization;
    using uFrame.MVVM;
    using uFrame.MVVM.Bindings;
    using uFrame.MVVM.ViewModels;
    using UniRx;
    using UnityEngine;
    
    
    public partial class MagicWeaponSystemViewModelBase : SkillEntityViewModel {
        
        private P<System.Object> _magicWeaponListProperty;
        
        public MagicWeaponSystemViewModelBase(uFrame.Kernel.IEventAggregator aggregator) : 
                base(aggregator) {
        }
        
        public virtual P<System.Object> magicWeaponListProperty {
            get {
                return _magicWeaponListProperty;
            }
            set {
                _magicWeaponListProperty = value;
            }
        }
        
        public virtual object magicWeaponList {
            get {
                return magicWeaponListProperty.Value;
            }
            set {
                magicWeaponListProperty.Value = value;
            }
        }
        
        public override void Bind() {
            base.Bind();
            _magicWeaponListProperty = new P<System.Object>(this, "magicWeaponList");
        }
        
        public override void Read(uFrame.Kernel.Serialization.ISerializerStream stream) {
            base.Read(stream);
        }
        
        public override void Write(uFrame.Kernel.Serialization.ISerializerStream stream) {
            base.Write(stream);
        }
        
        protected override void FillCommands(System.Collections.Generic.List<uFrame.MVVM.ViewModels.ViewModelCommandInfo> list) {
            base.FillCommands(list);
        }
        
        protected override void FillProperties(System.Collections.Generic.List<uFrame.MVVM.ViewModels.ViewModelPropertyInfo> list) {
            base.FillProperties(list);
            // PropertiesChildItem
            list.Add(new ViewModelPropertyInfo(_magicWeaponListProperty, false, false, false, false));
        }
    }
    
    public partial class MagicWeaponSystemViewModel {
        
        public MagicWeaponSystemViewModel(uFrame.Kernel.IEventAggregator aggregator) : 
                base(aggregator) {
        }
    }
}
