// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using MagicFire.HuanHuoUFrame;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.IOC;
    using uFrame.Kernel;
    using uFrame.Kernel.Serialization;
    using uFrame.MVVM;
    using uFrame.MVVM.Bindings;
    using uFrame.MVVM.ViewModels;
    using UniRx;
    using UnityEngine;
    
    
    public partial class MonsterViewModelBase : SuperPowerEntityViewModel {
        
        private Signal<StartMoveCommand> _StartMove;
        
        private Signal<StopMoveCommand> _StopMove;
        
        public MonsterViewModelBase(uFrame.Kernel.IEventAggregator aggregator) : 
                base(aggregator) {
        }
        
        public virtual Signal<StartMoveCommand> StartMove {
            get {
                return _StartMove;
            }
            set {
                _StartMove = value;
            }
        }
        
        public virtual Signal<StopMoveCommand> StopMove {
            get {
                return _StopMove;
            }
            set {
                _StopMove = value;
            }
        }
        
        public override void Bind() {
            base.Bind();
            this.StartMove = new Signal<StartMoveCommand>(this);
            this.StopMove = new Signal<StopMoveCommand>(this);
        }
        
        public virtual void Execute(StartMoveCommand argument) {
            this.StartMove.OnNext(argument);
        }
        
        public virtual void Execute(StopMoveCommand argument) {
            this.StopMove.OnNext(argument);
        }
        
        public virtual void StartMove_() {
            var cmd = new StartMoveCommand();
            this.StartMove.OnNext(cmd);
        }
        
        public virtual void StopMove_() {
            var cmd = new StopMoveCommand();
            this.StopMove.OnNext(cmd);
        }
        
        public override void Read(uFrame.Kernel.Serialization.ISerializerStream stream) {
            base.Read(stream);
        }
        
        public override void Write(uFrame.Kernel.Serialization.ISerializerStream stream) {
            base.Write(stream);
        }
        
        protected override void FillCommands(System.Collections.Generic.List<uFrame.MVVM.ViewModels.ViewModelCommandInfo> list) {
            base.FillCommands(list);
            list.Add(new ViewModelCommandInfo("StartMove", StartMove) { ParameterType = typeof(StartMoveCommand) });
            list.Add(new ViewModelCommandInfo("StopMove", StopMove) { ParameterType = typeof(StopMoveCommand) });
        }
        
        protected override void FillProperties(System.Collections.Generic.List<uFrame.MVVM.ViewModels.ViewModelPropertyInfo> list) {
            base.FillProperties(list);
        }
    }
    
    public partial class MonsterViewModel {
        
        public MonsterViewModel(uFrame.Kernel.IEventAggregator aggregator) : 
                base(aggregator) {
        }
    }
}
