// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using MagicFire.HuanHuoUFrame;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.IOC;
    using uFrame.Kernel;
    using uFrame.Kernel.Serialization;
    using uFrame.MVVM;
    using uFrame.MVVM.Bindings;
    using uFrame.MVVM.ViewModels;
    using UniRx;
    using UnityEngine;
    
    
    public partial class MotionSystemViewModelBase : SuperPowerEntityViewModel {
        
        private P<Int32> _canMoveProperty;
        
        private Signal<OnStopMoveCommand> _OnStopMove;
        
        private Signal<DoMoveCommand> _DoMove;
        
        public MotionSystemViewModelBase(uFrame.Kernel.IEventAggregator aggregator) : 
                base(aggregator) {
        }
        
        public virtual P<Int32> canMoveProperty {
            get {
                return _canMoveProperty;
            }
            set {
                _canMoveProperty = value;
            }
        }
        
        public virtual Int32 canMove {
            get {
                return canMoveProperty.Value;
            }
            set {
                canMoveProperty.Value = value;
            }
        }
        
        public virtual Signal<OnStopMoveCommand> OnStopMove {
            get {
                return _OnStopMove;
            }
            set {
                _OnStopMove = value;
            }
        }
        
        public virtual Signal<DoMoveCommand> DoMove {
            get {
                return _DoMove;
            }
            set {
                _DoMove = value;
            }
        }
        
        public override void Bind() {
            base.Bind();
            this.OnStopMove = new Signal<OnStopMoveCommand>(this);
            this.DoMove = new Signal<DoMoveCommand>(this);
            _canMoveProperty = new P<Int32>(this, "canMove");
        }
        
        public virtual void Execute(OnStopMoveCommand argument) {
            this.OnStopMove.OnNext(argument);
        }
        
        public virtual void Execute(DoMoveCommand argument) {
            this.DoMove.OnNext(argument);
        }
        
        public virtual void OnStopMove_() {
            var cmd = new OnStopMoveCommand();
            this.OnStopMove.OnNext(cmd);
        }
        
        public virtual void DoMove_(Vector3 Point) {
            var cmd = new DoMoveCommand();
            cmd.Point = Point;
            this.DoMove.OnNext(cmd);
        }
        
        public override void Read(uFrame.Kernel.Serialization.ISerializerStream stream) {
            base.Read(stream);
            this.canMove = stream.DeserializeInt("canMove");;
        }
        
        public override void Write(uFrame.Kernel.Serialization.ISerializerStream stream) {
            base.Write(stream);
            stream.SerializeInt("canMove", this.canMove);
        }
        
        protected override void FillCommands(System.Collections.Generic.List<uFrame.MVVM.ViewModels.ViewModelCommandInfo> list) {
            base.FillCommands(list);
            list.Add(new ViewModelCommandInfo("OnStopMove", OnStopMove) { ParameterType = typeof(OnStopMoveCommand) });
            list.Add(new ViewModelCommandInfo("DoMove", DoMove) { ParameterType = typeof(DoMoveCommand) });
        }
        
        protected override void FillProperties(System.Collections.Generic.List<uFrame.MVVM.ViewModels.ViewModelPropertyInfo> list) {
            base.FillProperties(list);
            // PropertiesChildItem
            list.Add(new ViewModelPropertyInfo(_canMoveProperty, false, false, false, false));
        }
    }
    
    public partial class MotionSystemViewModel {
        
        public MotionSystemViewModel(uFrame.Kernel.IEventAggregator aggregator) : 
                base(aggregator) {
        }
    }
}
