// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using MagicFire.HuanHuoUFrame;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.IOC;
    using uFrame.Kernel;
    using uFrame.Kernel.Serialization;
    using uFrame.MVVM;
    using uFrame.MVVM.Bindings;
    using uFrame.MVVM.ViewModels;
    using UniRx;
    using UnityEngine;
    
    
    public partial class SuperPowerEntityViewModelBase : HealthEntityViewModel {
        
        private P<Int32> _MSPProperty;
        
        private P<Int32> _MSP_MaxProperty;
        
        private P<Int32> _SP_MaxProperty;
        
        private P<Int32> _SPProperty;
        
        public SuperPowerEntityViewModelBase(uFrame.Kernel.IEventAggregator aggregator) : 
                base(aggregator) {
        }
        
        public virtual P<Int32> MSPProperty {
            get {
                return _MSPProperty;
            }
            set {
                _MSPProperty = value;
            }
        }
        
        public virtual P<Int32> MSP_MaxProperty {
            get {
                return _MSP_MaxProperty;
            }
            set {
                _MSP_MaxProperty = value;
            }
        }
        
        public virtual P<Int32> SP_MaxProperty {
            get {
                return _SP_MaxProperty;
            }
            set {
                _SP_MaxProperty = value;
            }
        }
        
        public virtual P<Int32> SPProperty {
            get {
                return _SPProperty;
            }
            set {
                _SPProperty = value;
            }
        }
        
        public virtual Int32 MSP {
            get {
                return MSPProperty.Value;
            }
            set {
                MSPProperty.Value = value;
            }
        }
        
        public virtual Int32 MSP_Max {
            get {
                return MSP_MaxProperty.Value;
            }
            set {
                MSP_MaxProperty.Value = value;
            }
        }
        
        public virtual Int32 SP_Max {
            get {
                return SP_MaxProperty.Value;
            }
            set {
                SP_MaxProperty.Value = value;
            }
        }
        
        public virtual Int32 SP {
            get {
                return SPProperty.Value;
            }
            set {
                SPProperty.Value = value;
            }
        }
        
        public override void Bind() {
            base.Bind();
            _MSPProperty = new P<Int32>(this, "MSP");
            _MSP_MaxProperty = new P<Int32>(this, "MSP_Max");
            _SP_MaxProperty = new P<Int32>(this, "SP_Max");
            _SPProperty = new P<Int32>(this, "SP");
        }
        
        public override void Read(uFrame.Kernel.Serialization.ISerializerStream stream) {
            base.Read(stream);
            this.MSP = stream.DeserializeInt("MSP");;
            this.MSP_Max = stream.DeserializeInt("MSP_Max");;
            this.SP_Max = stream.DeserializeInt("SP_Max");;
            this.SP = stream.DeserializeInt("SP");;
        }
        
        public override void Write(uFrame.Kernel.Serialization.ISerializerStream stream) {
            base.Write(stream);
            stream.SerializeInt("MSP", this.MSP);
            stream.SerializeInt("MSP_Max", this.MSP_Max);
            stream.SerializeInt("SP_Max", this.SP_Max);
            stream.SerializeInt("SP", this.SP);
        }
        
        protected override void FillCommands(System.Collections.Generic.List<uFrame.MVVM.ViewModels.ViewModelCommandInfo> list) {
            base.FillCommands(list);
        }
        
        protected override void FillProperties(System.Collections.Generic.List<uFrame.MVVM.ViewModels.ViewModelPropertyInfo> list) {
            base.FillProperties(list);
            // PropertiesChildItem
            list.Add(new ViewModelPropertyInfo(_MSPProperty, false, false, false, false));
            // PropertiesChildItem
            list.Add(new ViewModelPropertyInfo(_MSP_MaxProperty, false, false, false, false));
            // PropertiesChildItem
            list.Add(new ViewModelPropertyInfo(_SP_MaxProperty, false, false, false, false));
            // PropertiesChildItem
            list.Add(new ViewModelPropertyInfo(_SPProperty, false, false, false, false));
        }
    }
    
    public partial class SuperPowerEntityViewModel {
        
        public SuperPowerEntityViewModel(uFrame.Kernel.IEventAggregator aggregator) : 
                base(aggregator) {
        }
    }
}
