// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using MagicFire.HuanHuoUFrame;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class LoginSceneBase : uFrame.Kernel.Scene {
        
        public override string DefaultKernelScene {
            get {
                return "MagicFire.HuanHuoUFrameKernelScene";
            }
        }
        
        public virtual LoginSceneSettings Settings {
            get {
                return _SettingsObject as LoginSceneSettings;
            }
            set {
                _SettingsObject = value;
            }
        }
    }
    
    public class MuLingCunSpaceBase : uFrame.Kernel.Scene {
        
        public override string DefaultKernelScene {
            get {
                return "MagicFire.HuanHuoUFrameKernelScene";
            }
        }
        
        public virtual MuLingCunSpaceSettings Settings {
            get {
                return _SettingsObject as MuLingCunSpaceSettings;
            }
            set {
                _SettingsObject = value;
            }
        }
    }
    
    public class YunLingZongSpaceBase : uFrame.Kernel.Scene {
        
        public override string DefaultKernelScene {
            get {
                return "MagicFire.HuanHuoUFrameKernelScene";
            }
        }
        
        public virtual YunLingZongSpaceSettings Settings {
            get {
                return _SettingsObject as YunLingZongSpaceSettings;
            }
            set {
                _SettingsObject = value;
            }
        }
    }
}
