// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using MagicFire.HuanHuoUFrame;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.IOC;
    using uFrame.Kernel;
    using uFrame.Kernel.Serialization;
    using uFrame.MVVM;
    using UnityEngine;
    
    
    public class LoginSceneLoaderBase : SceneLoader<LoginScene> {
        
        protected override IEnumerator LoadScene(LoginScene scene, Action<float, string> progressDelegate) {
            yield break;
        }
        
        protected override IEnumerator UnloadScene(LoginScene scene, Action<float, string> progressDelegate) {
            yield break;
        }
    }
    
    public class MuLingCunSpaceLoaderBase : SceneLoader<MuLingCunSpace> {
        
        protected override IEnumerator LoadScene(MuLingCunSpace scene, Action<float, string> progressDelegate) {
            yield break;
        }
        
        protected override IEnumerator UnloadScene(MuLingCunSpace scene, Action<float, string> progressDelegate) {
            yield break;
        }
    }
    
    public class YunLingZongSpaceLoaderBase : SceneLoader<YunLingZongSpace> {
        
        protected override IEnumerator LoadScene(YunLingZongSpace scene, Action<float, string> progressDelegate) {
            yield break;
        }
        
        protected override IEnumerator UnloadScene(YunLingZongSpace scene, Action<float, string> progressDelegate) {
            yield break;
        }
    }
}
