// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using MagicFire.HuanHuoUFrame;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Json;
    using uFrame.Kernel;
    using uFrame.Kernel.Serialization;
    using uFrame.MVVM;
    using uFrame.MVVM.Bindings;
    
    
    public partial class set_directionEventBase : uFrame.MVVM.IJSonSerializable {
        
        private KBEngine.Entity _Entity;
        
        public KBEngine.Entity Entity {
            get {
                return _Entity;
            }
            set {
                _Entity = value;
            }
        }
        
        public virtual string Serialize() {
            var jsonObject = new JSONClass();
            return jsonObject.ToString();
        }
        
        public virtual void Deserialize(string json) {
        }
    }
    
    public partial class OnMainAvatarEnterWorldEventBase : uFrame.MVVM.IJSonSerializable {
        
        private KBEngine.Entity _Entity;
        
        public KBEngine.Entity Entity {
            get {
                return _Entity;
            }
            set {
                _Entity = value;
            }
        }
        
        public virtual string Serialize() {
            var jsonObject = new JSONClass();
            return jsonObject.ToString();
        }
        
        public virtual void Deserialize(string json) {
        }
    }
    
    public partial class onEnterWorldEventBase : uFrame.MVVM.IJSonSerializable {
        
        private KBEngine.Entity _Entity;
        
        public KBEngine.Entity Entity {
            get {
                return _Entity;
            }
            set {
                _Entity = value;
            }
        }
        
        public virtual string Serialize() {
            var jsonObject = new JSONClass();
            return jsonObject.ToString();
        }
        
        public virtual void Deserialize(string json) {
        }
    }
    
    public partial class OnLoginSuccessfullyEventBase : uFrame.MVVM.IJSonSerializable {
        
        public virtual string Serialize() {
            var jsonObject = new JSONClass();
            return jsonObject.ToString();
        }
        
        public virtual void Deserialize(string json) {
        }
    }
    
    public partial class set_positionEventBase : uFrame.MVVM.IJSonSerializable {
        
        private KBEngine.Entity _Entity;
        
        public KBEngine.Entity Entity {
            get {
                return _Entity;
            }
            set {
                _Entity = value;
            }
        }
        
        public virtual string Serialize() {
            var jsonObject = new JSONClass();
            return jsonObject.ToString();
        }
        
        public virtual void Deserialize(string json) {
        }
    }
    
    public partial class updatePositionEventBase : uFrame.MVVM.IJSonSerializable {
        
        private KBEngine.Entity _Entity;
        
        public KBEngine.Entity Entity {
            get {
                return _Entity;
            }
            set {
                _Entity = value;
            }
        }
        
        public virtual string Serialize() {
            var jsonObject = new JSONClass();
            return jsonObject.ToString();
        }
        
        public virtual void Deserialize(string json) {
        }
    }
    
    public partial class OnMainAvatarLeaveSpaceEventBase : uFrame.MVVM.IJSonSerializable {
        
        public virtual string Serialize() {
            var jsonObject = new JSONClass();
            return jsonObject.ToString();
        }
        
        public virtual void Deserialize(string json) {
        }
    }
    
    public partial class OnMainAvatarEnterSpaceEventBase : uFrame.MVVM.IJSonSerializable {
        
        private Int32 _SpaceId;
        
        private String _SpaceName;
        
        public Int32 SpaceId {
            get {
                return _SpaceId;
            }
            set {
                _SpaceId = value;
            }
        }
        
        public String SpaceName {
            get {
                return _SpaceName;
            }
            set {
                _SpaceName = value;
            }
        }
        
        public virtual string Serialize() {
            var jsonObject = new JSONClass();
            jsonObject.Add("SpaceId", new JSONData(this.SpaceId));
            jsonObject.Add("SpaceName", new JSONData(this.SpaceName));
            return jsonObject.ToString();
        }
        
        public virtual void Deserialize(string json) {
            var node = JSON.Parse(json);
            if (node["SpaceId"] != null) {
                this.SpaceId = node["SpaceId"].AsInt;
            }
            if (node["SpaceName"] != null) {
                this.SpaceName = node["SpaceName"].AsString;
            }
        }
    }
    
    public partial class ASkillBase : uFrame.MVVM.IJSonSerializable {
        
        private Int32 _skillLevel;
        
        private Int32 _skillIndex;
        
        public Int32 skillLevel {
            get {
                return _skillLevel;
            }
            set {
                _skillLevel = value;
            }
        }
        
        public Int32 skillIndex {
            get {
                return _skillIndex;
            }
            set {
                _skillIndex = value;
            }
        }
        
        public virtual string Serialize() {
            var jsonObject = new JSONClass();
            jsonObject.Add("skillLevel", new JSONData(this.skillLevel));
            jsonObject.Add("skillIndex", new JSONData(this.skillIndex));
            return jsonObject.ToString();
        }
        
        public virtual void Deserialize(string json) {
            var node = JSON.Parse(json);
            if (node["skillLevel"] != null) {
                this.skillLevel = node["skillLevel"].AsInt;
            }
            if (node["skillIndex"] != null) {
                this.skillIndex = node["skillIndex"].AsInt;
            }
        }
    }
    
    public partial class onLeaveWorldEventBase : uFrame.MVVM.IJSonSerializable {
        
        private KBEngine.Entity _Entity;
        
        public KBEngine.Entity Entity {
            get {
                return _Entity;
            }
            set {
                _Entity = value;
            }
        }
        
        public virtual string Serialize() {
            var jsonObject = new JSONClass();
            return jsonObject.ToString();
        }
        
        public virtual void Deserialize(string json) {
        }
    }
}
