// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using MagicFire.HuanHuoUFrame;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using uFrame.Kernel.Serialization;
    using uFrame.MVVM;
    using uFrame.MVVM.Bindings;
    using uFrame.MVVM.Services;
    using uFrame.MVVM.ViewModels;
    using UniRx;
    using UnityEngine;
    
    
    public class NewViewComponentNodeBase : uFrame.MVVM.Views.ViewComponent {
        
        public virtual EntityCommonViewModel EntityCommon {
            get {
                return (EntityCommonViewModel)this.View.ViewModelObject;
            }
        }
        
        public virtual void ExecuteOnDestroy(OnDestroyCommand command) {
            command.Sender = EntityCommon;
            EntityCommon.OnDestroy.OnNext(command);
        }
        
        public virtual void ExecuteOnLeaveWorld(OnLeaveWorldCommand command) {
            command.Sender = EntityCommon;
            EntityCommon.OnLeaveWorld.OnNext(command);
        }
    }
}
