// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using MagicFire.HuanHuoUFrame;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using uFrame.Kernel.Serialization;
    using uFrame.MVVM;
    using uFrame.MVVM.Bindings;
    using uFrame.MVVM.Services;
    using uFrame.MVVM.ViewModels;
    using UniRx;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class LoginPanelBase : uFrame.MVVM.Views.ViewBase {
        
        [UnityEngine.SerializeField()]
        [uFrame.MVVM.Attributes.UFGroup("View Model Properties")]
        [UnityEngine.HideInInspector()]
        public String _Username;
        
        [UnityEngine.SerializeField()]
        [uFrame.MVVM.Attributes.UFGroup("View Model Properties")]
        [UnityEngine.HideInInspector()]
        public String _CurrentServerIp;
        
        [UnityEngine.SerializeField()]
        [uFrame.MVVM.Attributes.UFGroup("View Model Properties")]
        [UnityEngine.HideInInspector()]
        public MagicFire.HuanHuoUFrame.RegistePanel _RegistePanel;
        
        [UnityEngine.SerializeField()]
        [uFrame.MVVM.Attributes.UFGroup("View Model Properties")]
        [UnityEngine.HideInInspector()]
        public Int32 _CurrentServerNum;
        
        [UnityEngine.SerializeField()]
        [uFrame.MVVM.Attributes.UFGroup("View Model Properties")]
        [UnityEngine.HideInInspector()]
        public String _Password;
        
        [UnityEngine.SerializeField()]
        [uFrame.MVVM.Attributes.UFGroup("View Model Properties")]
        [UnityEngine.HideInInspector()]
        public String _SecondPassword;
        
        [UnityEngine.SerializeField()]
        [uFrame.MVVM.Attributes.UFGroup("View Model Properties")]
        [UnityEngine.HideInInspector()]
        public UnityEngine.UI.Dropdown _ServerList;
        
        [uFrame.MVVM.Attributes.UFToggleGroup("UserLogin")]
        [UnityEngine.HideInInspector()]
        public bool _BindUserLogin = true;
        
        [uFrame.MVVM.Attributes.UFGroup("UserLogin")]
        [UnityEngine.SerializeField()]
        [UnityEngine.HideInInspector()]
        [UnityEngine.Serialization.FormerlySerializedAsAttribute("_UserLoginbutton")]
        protected UnityEngine.UI.Button _UserLoginButton;
        
        [uFrame.MVVM.Attributes.UFToggleGroup("Test03Login")]
        [UnityEngine.HideInInspector()]
        public bool _BindTest03Login = true;
        
        [uFrame.MVVM.Attributes.UFGroup("Test03Login")]
        [UnityEngine.SerializeField()]
        [UnityEngine.HideInInspector()]
        [UnityEngine.Serialization.FormerlySerializedAsAttribute("_Test03Loginbutton")]
        protected UnityEngine.UI.Button _Test03LoginButton;
        
        [uFrame.MVVM.Attributes.UFToggleGroup("Test02Login")]
        [UnityEngine.HideInInspector()]
        public bool _BindTest02Login = true;
        
        [uFrame.MVVM.Attributes.UFGroup("Test02Login")]
        [UnityEngine.SerializeField()]
        [UnityEngine.HideInInspector()]
        [UnityEngine.Serialization.FormerlySerializedAsAttribute("_Test02Loginbutton")]
        protected UnityEngine.UI.Button _Test02LoginButton;
        
        [uFrame.MVVM.Attributes.UFToggleGroup("Test01Login")]
        [UnityEngine.HideInInspector()]
        public bool _BindTest01Login = true;
        
        [uFrame.MVVM.Attributes.UFGroup("Test01Login")]
        [UnityEngine.SerializeField()]
        [UnityEngine.HideInInspector()]
        [UnityEngine.Serialization.FormerlySerializedAsAttribute("_Test01Loginbutton")]
        protected UnityEngine.UI.Button _Test01LoginButton;
        
        [uFrame.MVVM.Attributes.UFToggleGroup("ShowRegistePanel")]
        [UnityEngine.HideInInspector()]
        public bool _BindShowRegistePanel = true;
        
        [uFrame.MVVM.Attributes.UFGroup("ShowRegistePanel")]
        [UnityEngine.SerializeField()]
        [UnityEngine.HideInInspector()]
        [UnityEngine.Serialization.FormerlySerializedAsAttribute("_ShowRegistePanelbutton")]
        protected UnityEngine.UI.Button _ShowRegistePanelButton;
        
        [uFrame.MVVM.Attributes.UFToggleGroup("Username")]
        [UnityEngine.HideInInspector()]
        public bool _BindUsername = true;
        
        [uFrame.MVVM.Attributes.UFGroup("Username")]
        [UnityEngine.SerializeField()]
        [UnityEngine.HideInInspector()]
        [UnityEngine.Serialization.FormerlySerializedAsAttribute("_Usernameinput")]
        protected UnityEngine.UI.InputField _UsernameInput;
        
        [uFrame.MVVM.Attributes.UFToggleGroup("Password")]
        [UnityEngine.HideInInspector()]
        public bool _BindPassword = true;
        
        [uFrame.MVVM.Attributes.UFGroup("Password")]
        [UnityEngine.SerializeField()]
        [UnityEngine.HideInInspector()]
        [UnityEngine.Serialization.FormerlySerializedAsAttribute("_Passwordinput")]
        protected UnityEngine.UI.InputField _PasswordInput;
        
        public override string DefaultIdentifier {
            get {
                return "UserLoginScreen";
            }
        }
        
        public override System.Type ViewModelType {
            get {
                return typeof(UserLoginScreenViewModel);
            }
        }
        
        public UserLoginScreenViewModel UserLoginScreen {
            get {
                return (UserLoginScreenViewModel)ViewModelObject;
            }
        }
        
        protected override void InitializeViewModel(uFrame.MVVM.ViewModels.ViewModel model) {
            base.InitializeViewModel(model);
            // NOTE: this method is only invoked if the 'Initialize ViewModel' is checked in the inspector.
            // var vm = model as UserLoginScreenViewModel;
            // This method is invoked when applying the data from the inspector to the viewmodel.  Add any view-specific customizations here.
            var loginpanel = ((UserLoginScreenViewModel)model);
            loginpanel.Username = this._Username;
            loginpanel.CurrentServerIp = this._CurrentServerIp;
            loginpanel.RegistePanel = this._RegistePanel;
            loginpanel.CurrentServerNum = this._CurrentServerNum;
            loginpanel.Password = this._Password;
            loginpanel.SecondPassword = this._SecondPassword;
            loginpanel.ServerList = this._ServerList;
        }
        
        public override void Bind() {
            base.Bind();
            // Use this.UserLoginScreen to access the viewmodel.
            // Use this method to subscribe to the view-model.
            // Any designer bindings are created in the base implementation.
            if (_BindUserLogin) {
                this.BindButtonToCommand(_UserLoginButton, this.UserLoginScreen.UserLogin);
            }
            if (_BindTest03Login) {
                this.BindButtonToCommand(_Test03LoginButton, this.UserLoginScreen.Test03Login);
            }
            if (_BindTest02Login) {
                this.BindButtonToCommand(_Test02LoginButton, this.UserLoginScreen.Test02Login);
            }
            if (_BindTest01Login) {
                this.BindButtonToCommand(_Test01LoginButton, this.UserLoginScreen.Test01Login);
            }
            if (_BindShowRegistePanel) {
                this.BindButtonToCommand(_ShowRegistePanelButton, this.UserLoginScreen.ShowRegistePanel);
            }
            if (_BindUsername) {
                this.BindInputFieldToProperty(_UsernameInput, this.UserLoginScreen.UsernameProperty);
            }
            if (_BindPassword) {
                this.BindInputFieldToProperty(_PasswordInput, this.UserLoginScreen.PasswordProperty);
            }
        }
        
        public virtual void ExecuteUserLogin(UserLoginCommand command) {
            command.Sender = UserLoginScreen;
            UserLoginScreen.UserLogin.OnNext(command);
        }
        
        public virtual void ExecuteCloseRegistePanel(CloseRegistePanelCommand command) {
            command.Sender = UserLoginScreen;
            UserLoginScreen.CloseRegistePanel.OnNext(command);
        }
        
        public virtual void ExecuteShowRegistePanel(ShowRegistePanelCommand command) {
            command.Sender = UserLoginScreen;
            UserLoginScreen.ShowRegistePanel.OnNext(command);
        }
        
        public virtual void ExecuteTest01Login(Test01LoginCommand command) {
            command.Sender = UserLoginScreen;
            UserLoginScreen.Test01Login.OnNext(command);
        }
        
        public virtual void ExecuteTest02Login(Test02LoginCommand command) {
            command.Sender = UserLoginScreen;
            UserLoginScreen.Test02Login.OnNext(command);
        }
        
        public virtual void ExecuteTest03Login(Test03LoginCommand command) {
            command.Sender = UserLoginScreen;
            UserLoginScreen.Test03Login.OnNext(command);
        }
        
        public virtual void ExecuteRegisteUser(RegisteUserCommand command) {
            command.Sender = UserLoginScreen;
            UserLoginScreen.RegisteUser.OnNext(command);
        }
    }
}
