// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class MovablePanelControllerBase : uFrame.MVVM.Controller {
        
        private uFrame.MVVM.ViewModels.IViewModelManager<MovablePanelViewModel> _MovablePanelViewModelManager;
        
        private MessageBoxViewModel _MessageBox;
        
        private UserLoginScreenViewModel _UserLoginScreen;
        
        private RpgMainScreenViewModel _RpgMainScreen;
        
        [uFrame.IOC.InjectAttribute("MovablePanel")]
        public uFrame.MVVM.ViewModels.IViewModelManager<MovablePanelViewModel> MovablePanelViewModelManager {
            get {
                return _MovablePanelViewModelManager;
            }
            set {
                _MovablePanelViewModelManager = value;
            }
        }
        
        [uFrame.IOC.InjectAttribute("MessageBox")]
        public MessageBoxViewModel MessageBox {
            get {
                return _MessageBox;
            }
            set {
                _MessageBox = value;
            }
        }
        
        [uFrame.IOC.InjectAttribute("UserLoginScreen")]
        public UserLoginScreenViewModel UserLoginScreen {
            get {
                return _UserLoginScreen;
            }
            set {
                _UserLoginScreen = value;
            }
        }
        
        [uFrame.IOC.InjectAttribute("RpgMainScreen")]
        public RpgMainScreenViewModel RpgMainScreen {
            get {
                return _RpgMainScreen;
            }
            set {
                _RpgMainScreen = value;
            }
        }
        
        public IEnumerable<MovablePanelViewModel> MovablePanelViewModels {
            get {
                return MovablePanelViewModelManager.ViewModels;
            }
        }
        
        public override void Setup() {
            base.Setup();
            // This is called when the controller is created
        }
        
        public override void Initialize(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.Initialize(viewModel);
            // This is called when a viewmodel is created
            this.InitializeMovablePanel(((MovablePanelViewModel)(viewModel)));
        }
        
        public virtual MovablePanelViewModel CreateMovablePanel() {
            return ((MovablePanelViewModel)(this.Create(Guid.NewGuid().ToString())));
        }
        
        public override uFrame.MVVM.ViewModels.ViewModel CreateEmpty() {
            return new MovablePanelViewModel(this.EventAggregator);
        }
        
        public virtual void InitializeMovablePanel(MovablePanelViewModel viewModel) {
            // This is called when a MovablePanelViewModel is created
            MovablePanelViewModelManager.Add(viewModel);
        }
        
        public override void DisposingViewModel(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.DisposingViewModel(viewModel);
            MovablePanelViewModelManager.Remove(viewModel);
        }
    }
}
