// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using MagicFire.HuanHuoUFrame;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.Components;
    using uFrame.Json;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(5)]
    [uFrame.Attributes.uFrameIdentifier("366cde25-2d65-42e2-bce7-dc326c858508")]
    public partial class DragBarComponent : uFrame.ECS.Components.EcsComponent {
        
        [UnityEngine.SerializeField()]
        private UnityEngine.GameObject _MoveObject;
        
        private Subject<PropertyChangedEvent<UnityEngine.GameObject>> _MoveObjectObservable;
        
        private PropertyChangedEvent<UnityEngine.GameObject> _MoveObjectEvent;
        
        public override int ComponentId {
            get {
                return 5;
            }
        }
        
        public IObservable<PropertyChangedEvent<UnityEngine.GameObject>> MoveObjectObservable {
            get {
                return _MoveObjectObservable ?? (_MoveObjectObservable = new Subject<PropertyChangedEvent<UnityEngine.GameObject>>());
            }
        }
        
        public UnityEngine.GameObject MoveObject {
            get {
                return _MoveObject;
            }
            set {
                SetMoveObject(value);
            }
        }
        
        public virtual void SetMoveObject(UnityEngine.GameObject value) {
            SetProperty(ref _MoveObject, value, ref _MoveObjectEvent, _MoveObjectObservable);
        }
    }
}
