// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.Components;
    using uFrame.Json;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(12)]
    [uFrame.Attributes.uFrameIdentifier("b59eaae7-fe3d-4ebd-bdcb-333fbbe4e434")]
    public partial class RightKeyMenuComponent : uFrame.ECS.Components.EcsComponent {
        
        public override int ComponentId {
            get {
                return 12;
            }
        }
    }
}
