// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using MagicFire.HuanHuoUFrame;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.Components;
    using uFrame.Json;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(10)]
    [uFrame.Attributes.uFrameIdentifier("7d36b326-a35f-40ce-8348-d8ac84731d6d")]
    public partial class RpgInteractiveComponent : uFrame.ECS.Components.EcsComponent {
        
        [UnityEngine.SerializeField()]
        private CallType _CallType;
        
        [UnityEngine.SerializeField()]
        private String _RemoteCallName;
        
        [UnityEngine.SerializeField()]
        private uFrame.MVVM.Views.ViewBase _EntityView;
        
        private Subject<PropertyChangedEvent<CallType>> _CallTypeObservable;
        
        private PropertyChangedEvent<CallType> _CallTypeEvent;
        
        private Subject<PropertyChangedEvent<String>> _RemoteCallNameObservable;
        
        private PropertyChangedEvent<String> _RemoteCallNameEvent;
        
        private Subject<PropertyChangedEvent<uFrame.MVVM.Views.ViewBase>> _EntityViewObservable;
        
        private PropertyChangedEvent<uFrame.MVVM.Views.ViewBase> _EntityViewEvent;
        
        public override int ComponentId {
            get {
                return 10;
            }
        }
        
        public IObservable<PropertyChangedEvent<CallType>> CallTypeObservable {
            get {
                return _CallTypeObservable ?? (_CallTypeObservable = new Subject<PropertyChangedEvent<CallType>>());
            }
        }
        
        public IObservable<PropertyChangedEvent<String>> RemoteCallNameObservable {
            get {
                return _RemoteCallNameObservable ?? (_RemoteCallNameObservable = new Subject<PropertyChangedEvent<String>>());
            }
        }
        
        public IObservable<PropertyChangedEvent<uFrame.MVVM.Views.ViewBase>> EntityViewObservable {
            get {
                return _EntityViewObservable ?? (_EntityViewObservable = new Subject<PropertyChangedEvent<uFrame.MVVM.Views.ViewBase>>());
            }
        }
        
        public CallType CallType {
            get {
                return _CallType;
            }
            set {
                SetCallType(value);
            }
        }
        
        public String RemoteCallName {
            get {
                return _RemoteCallName;
            }
            set {
                SetRemoteCallName(value);
            }
        }
        
        public uFrame.MVVM.Views.ViewBase EntityView {
            get {
                return _EntityView;
            }
            set {
                SetEntityView(value);
            }
        }
        
        public virtual void SetCallType(CallType value) {
            SetProperty(ref _CallType, value, ref _CallTypeEvent, _CallTypeObservable);
        }
        
        public virtual void SetRemoteCallName(String value) {
            SetProperty(ref _RemoteCallName, value, ref _RemoteCallNameEvent, _RemoteCallNameObservable);
        }
        
        public virtual void SetEntityView(uFrame.MVVM.Views.ViewBase value) {
            SetProperty(ref _EntityView, value, ref _EntityViewEvent, _EntityViewObservable);
        }
    }
}
