// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.Components;
    using uFrame.Json;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(8)]
    [uFrame.Attributes.uFrameIdentifier("123b54ac-8759-4def-9a3a-b746e9b8b856")]
    public partial class RpgLookAtPlayerComponent : uFrame.ECS.Components.EcsComponent {
        
        public override int ComponentId {
            get {
                return 8;
            }
        }
    }
}
