// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    
    
    [uFrame.Attributes.EventId(5)]
    public partial class ExitArenaEvent : object {
        
        [UnityEngine.SerializeField()]
        private UnityEngine.GameObject _ExitAvatar;
        
        public UnityEngine.GameObject ExitAvatar {
            get {
                return _ExitAvatar;
            }
            set {
                _ExitAvatar = value;
            }
        }
    }
}
