// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.EventId(11)]
    public partial class OnBagItemBeginDragEvent : object {
        
        [UnityEngine.SerializeField()]
        private Transform _BagItem;
        
        public Transform BagItem {
            get {
                return _BagItem;
            }
            set {
                _BagItem = value;
            }
        }
    }
}
