// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    
    
    [uFrame.Attributes.EventId(9)]
    public partial class ShowStorePanelEvent : object {
        
        [UnityEngine.SerializeField()]
        private OnPullStorePropListReturnCommand _StorePropListReturnCommand;
        
        public OnPullStorePropListReturnCommand StorePropListReturnCommand {
            get {
                return _StorePropListReturnCommand;
            }
            set {
                _StorePropListReturnCommand = value;
            }
        }
    }
}
