// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.EventId(15)]
    public partial class StartMoveEvent : object {
        
        [UnityEngine.SerializeField()]
        private Vector3 _Point;
        
        public Vector3 Point {
            get {
                return _Point;
            }
            set {
                _Point = value;
            }
        }
    }
}
