// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoMVVM {
    using MagicFire.HuanHuoMVVM;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Json;
    using uFrame.Kernel;
    using uFrame.Kernel.Serialization;
    using uFrame.MVVM;
    using uFrame.MVVM.Bindings;
    
    
    public partial class setdirectionEventBase : uFrame.MVVM.IJSonSerializable {
        
        private KBEngine.Entity _Entity;
        
        public KBEngine.Entity Entity {
            get {
                return _Entity;
            }
            set {
                _Entity = value;
            }
        }
        
        public virtual string Serialize() {
            var jsonObject = new JSONClass();
            return jsonObject.ToString();
        }
        
        public virtual void Deserialize(string json) {
        }
    }
    
    public partial class OnAvatarEnterWorldEventBase : uFrame.MVVM.IJSonSerializable {
        
        private KBEngine.Entity _Entity;
        
        public KBEngine.Entity Entity {
            get {
                return _Entity;
            }
            set {
                _Entity = value;
            }
        }
        
        public virtual string Serialize() {
            var jsonObject = new JSONClass();
            return jsonObject.ToString();
        }
        
        public virtual void Deserialize(string json) {
        }
    }
    
    public partial class onEnterWorldEventBase : uFrame.MVVM.IJSonSerializable {
        
        private KBEngine.Entity _Entity;
        
        public KBEngine.Entity Entity {
            get {
                return _Entity;
            }
            set {
                _Entity = value;
            }
        }
        
        public virtual string Serialize() {
            var jsonObject = new JSONClass();
            return jsonObject.ToString();
        }
        
        public virtual void Deserialize(string json) {
        }
    }
    
    public partial class OnLoginSuccessfullyEventBase : uFrame.MVVM.IJSonSerializable {
        
        public virtual string Serialize() {
            var jsonObject = new JSONClass();
            return jsonObject.ToString();
        }
        
        public virtual void Deserialize(string json) {
        }
    }
    
    public partial class setpositionEventBase : uFrame.MVVM.IJSonSerializable {
        
        private KBEngine.Entity _Entity;
        
        public KBEngine.Entity Entity {
            get {
                return _Entity;
            }
            set {
                _Entity = value;
            }
        }
        
        public virtual string Serialize() {
            var jsonObject = new JSONClass();
            return jsonObject.ToString();
        }
        
        public virtual void Deserialize(string json) {
        }
    }
    
    public partial class updatePositionEventBase : uFrame.MVVM.IJSonSerializable {
        
        private KBEngine.Entity _Entity;
        
        public KBEngine.Entity Entity {
            get {
                return _Entity;
            }
            set {
                _Entity = value;
            }
        }
        
        public virtual string Serialize() {
            var jsonObject = new JSONClass();
            return jsonObject.ToString();
        }
        
        public virtual void Deserialize(string json) {
        }
    }
    
    public partial class OnMainAvatarLeaveSpaceEventBase : uFrame.MVVM.IJSonSerializable {
        
        public virtual string Serialize() {
            var jsonObject = new JSONClass();
            return jsonObject.ToString();
        }
        
        public virtual void Deserialize(string json) {
        }
    }
    
    public partial class OnMainAvatarEnterSpaceEventBase : uFrame.MVVM.IJSonSerializable {
        
        private Int32 _SpaceId;
        
        private String _SpaceName;
        
        public Int32 SpaceId {
            get {
                return _SpaceId;
            }
            set {
                _SpaceId = value;
            }
        }
        
        public String SpaceName {
            get {
                return _SpaceName;
            }
            set {
                _SpaceName = value;
            }
        }
        
        public virtual string Serialize() {
            var jsonObject = new JSONClass();
            jsonObject.Add("SpaceId", new JSONData(this.SpaceId));
            jsonObject.Add("SpaceName", new JSONData(this.SpaceName));
            return jsonObject.ToString();
        }
        
        public virtual void Deserialize(string json) {
            var node = JSON.Parse(json);
            if (node["SpaceId"] != null) {
                this.SpaceId = node["SpaceId"].AsInt;
            }
            if (node["SpaceName"] != null) {
                this.SpaceName = node["SpaceName"].AsString;
            }
        }
    }
    
    public partial class onLeaveWorldEventBase : uFrame.MVVM.IJSonSerializable {
        
        private KBEngine.Entity _Entity;
        
        public KBEngine.Entity Entity {
            get {
                return _Entity;
            }
            set {
                _Entity = value;
            }
        }
        
        public virtual string Serialize() {
            var jsonObject = new JSONClass();
            return jsonObject.ToString();
        }
        
        public virtual void Deserialize(string json) {
        }
    }
}
