// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using MagicFire.HuanHuoUFrame;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.IOC;
    using uFrame.Kernel;
    using uFrame.MVVM;
    using uFrame.MVVM.ViewModels;
    using UniRx;
    using UnityEngine;
    
    
    public class RpgGameSystemLoaderBase : uFrame.Kernel.SystemLoader {
        
        private MessageBoxViewModel _MessageBox;
        
        private UserLoginScreenViewModel _UserLoginScreen;
        
        private RpgMainScreenViewModel _RpgMainScreen;
        
        private UserLoginScreenController _UserLoginScreenController;
        
        private MessageBoxController _MessageBoxController;
        
        private RpgMainScreenController _RpgMainScreenController;
        
        [uFrame.IOC.InjectAttribute("MessageBox")]
        public virtual MessageBoxViewModel MessageBox {
            get {
                if (this._MessageBox == null) {
                    this._MessageBox = this.CreateViewModel<MessageBoxViewModel>( "MessageBox");
                }
                return _MessageBox;
            }
        }
        
        [uFrame.IOC.InjectAttribute("UserLoginScreen")]
        public virtual UserLoginScreenViewModel UserLoginScreen {
            get {
                if (this._UserLoginScreen == null) {
                    this._UserLoginScreen = this.CreateViewModel<UserLoginScreenViewModel>( "UserLoginScreen");
                }
                return _UserLoginScreen;
            }
        }
        
        [uFrame.IOC.InjectAttribute("RpgMainScreen")]
        public virtual RpgMainScreenViewModel RpgMainScreen {
            get {
                if (this._RpgMainScreen == null) {
                    this._RpgMainScreen = this.CreateViewModel<RpgMainScreenViewModel>( "RpgMainScreen");
                }
                return _RpgMainScreen;
            }
        }
        
        [uFrame.IOC.InjectAttribute()]
        public virtual UserLoginScreenController UserLoginScreenController {
            get {
                if (_UserLoginScreenController==null) {
                    _UserLoginScreenController = Container.CreateInstance(typeof(UserLoginScreenController)) as UserLoginScreenController;;
                }
                return _UserLoginScreenController;
            }
            set {
                _UserLoginScreenController = value;
            }
        }
        
        [uFrame.IOC.InjectAttribute()]
        public virtual MessageBoxController MessageBoxController {
            get {
                if (_MessageBoxController==null) {
                    _MessageBoxController = Container.CreateInstance(typeof(MessageBoxController)) as MessageBoxController;;
                }
                return _MessageBoxController;
            }
            set {
                _MessageBoxController = value;
            }
        }
        
        [uFrame.IOC.InjectAttribute()]
        public virtual RpgMainScreenController RpgMainScreenController {
            get {
                if (_RpgMainScreenController==null) {
                    _RpgMainScreenController = Container.CreateInstance(typeof(RpgMainScreenController)) as RpgMainScreenController;;
                }
                return _RpgMainScreenController;
            }
            set {
                _RpgMainScreenController = value;
            }
        }
        
        public override void Load() {
            Container.RegisterViewModelManager<UserLoginScreenViewModel>(new ViewModelManager<UserLoginScreenViewModel>());
            Container.RegisterController<UserLoginScreenController>(UserLoginScreenController);
            Container.RegisterViewModelManager<MessageBoxViewModel>(new ViewModelManager<MessageBoxViewModel>());
            Container.RegisterController<MessageBoxController>(MessageBoxController);
            Container.RegisterViewModelManager<RpgMainScreenViewModel>(new ViewModelManager<RpgMainScreenViewModel>());
            Container.RegisterController<RpgMainScreenController>(RpgMainScreenController);
            Container.RegisterViewModel<MessageBoxViewModel>(MessageBox, "MessageBox");
            Container.RegisterViewModel<UserLoginScreenViewModel>(UserLoginScreen, "UserLoginScreen");
            Container.RegisterViewModel<RpgMainScreenViewModel>(RpgMainScreen, "RpgMainScreen");
        }
    }
}
