// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS.APIs;
    using uFrame.ECS.Components;
    using uFrame.ECS.Systems;
    using uFrame.Kernel;
    using UniRx;
    using UnityEngine;
    
    
    public partial class PanelSystemBase : uFrame.ECS.Systems.EcsSystem {
        
        private IEcsComponentManagerOf<DragBarComponent> _DragBarComponentManager;
        
        public IEcsComponentManagerOf<DragBarComponent> DragBarComponentManager {
            get {
                return _DragBarComponentManager;
            }
            set {
                _DragBarComponentManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            DragBarComponentManager = ComponentSystem.RegisterComponent<DragBarComponent>(5);
        }
    }
    
    [uFrame.Attributes.uFrameIdentifier("c280bad0-b927-409e-aac3-f6141865f8c5")]
    public partial class PanelSystem : PanelSystemBase {
        
        private static PanelSystem _Instance;
        
        public PanelSystem() {
            Instance = this;
        }
        
        public static PanelSystem Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
    }
}
