// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoUFrame {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS.APIs;
    using uFrame.ECS.Components;
    using uFrame.ECS.Systems;
    using uFrame.Kernel;
    using UniRx;
    using UnityEngine;
    
    
    public partial class RpgControlSystemBase : uFrame.ECS.Systems.EcsSystem {
        
        private IEcsComponentManagerOf<RpgMoveController> _RpgMoveControllerManager;
        
        private IEcsComponentManagerOf<RpgLookAtPlayerComponent> _RpgLookAtPlayerComponentManager;
        
        private IEcsComponentManagerOf<RpgTerrainComponent> _RpgTerrainComponentManager;
        
        private IEcsComponentManagerOf<RpgSkillController> _RpgSkillControllerManager;
        
        private IEcsComponentManagerOf<RpgInteractiveComponent> _RpgInteractiveComponentManager;
        
        private IEcsComponentManagerOf<RpgMovePointMarker> _RpgMovePointMarkerManager;
        
        private IEcsComponentManagerOf<RightKeyMenuComponent> _RightKeyMenuComponentManager;
        
        public IEcsComponentManagerOf<RpgMoveController> RpgMoveControllerManager {
            get {
                return _RpgMoveControllerManager;
            }
            set {
                _RpgMoveControllerManager = value;
            }
        }
        
        public IEcsComponentManagerOf<RpgLookAtPlayerComponent> RpgLookAtPlayerComponentManager {
            get {
                return _RpgLookAtPlayerComponentManager;
            }
            set {
                _RpgLookAtPlayerComponentManager = value;
            }
        }
        
        public IEcsComponentManagerOf<RpgTerrainComponent> RpgTerrainComponentManager {
            get {
                return _RpgTerrainComponentManager;
            }
            set {
                _RpgTerrainComponentManager = value;
            }
        }
        
        public IEcsComponentManagerOf<RpgSkillController> RpgSkillControllerManager {
            get {
                return _RpgSkillControllerManager;
            }
            set {
                _RpgSkillControllerManager = value;
            }
        }
        
        public IEcsComponentManagerOf<RpgInteractiveComponent> RpgInteractiveComponentManager {
            get {
                return _RpgInteractiveComponentManager;
            }
            set {
                _RpgInteractiveComponentManager = value;
            }
        }
        
        public IEcsComponentManagerOf<RpgMovePointMarker> RpgMovePointMarkerManager {
            get {
                return _RpgMovePointMarkerManager;
            }
            set {
                _RpgMovePointMarkerManager = value;
            }
        }
        
        public IEcsComponentManagerOf<RightKeyMenuComponent> RightKeyMenuComponentManager {
            get {
                return _RightKeyMenuComponentManager;
            }
            set {
                _RightKeyMenuComponentManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            RpgMoveControllerManager = ComponentSystem.RegisterComponent<RpgMoveController>(1);
            RpgLookAtPlayerComponentManager = ComponentSystem.RegisterComponent<RpgLookAtPlayerComponent>(8);
            RpgTerrainComponentManager = ComponentSystem.RegisterComponent<RpgTerrainComponent>(11);
            RpgSkillControllerManager = ComponentSystem.RegisterComponent<RpgSkillController>(7);
            RpgInteractiveComponentManager = ComponentSystem.RegisterComponent<RpgInteractiveComponent>(10);
            RpgMovePointMarkerManager = ComponentSystem.RegisterComponent<RpgMovePointMarker>(9);
            RightKeyMenuComponentManager = ComponentSystem.RegisterComponent<RightKeyMenuComponent>(12);
        }
    }
    
    [uFrame.Attributes.uFrameIdentifier("2cd840ab-21c7-4ec9-8561-4f956214683a")]
    public partial class RpgControlSystem : RpgControlSystemBase {
        
        private static RpgControlSystem _Instance;
        
        public RpgControlSystem() {
            Instance = this;
        }
        
        public static RpgControlSystem Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
    }
}
