// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagicFire.HuanHuoMVVM {
    using MagicFire.HuanHuoMVVM;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.IOC;
    using uFrame.Kernel;
    using uFrame.MVVM;
    using uFrame.MVVM.ViewModels;
    using UniRx;
    using UnityEngine;
    
    
    public class RpgGameSystemLoaderBase : uFrame.Kernel.SystemLoader {
        
        private UserLoginScreenViewModel _UserLoginScreen;
        
        private UserLoginScreenController _UserLoginScreenController;
        
        [uFrame.IOC.InjectAttribute("UserLoginScreen")]
        public virtual UserLoginScreenViewModel UserLoginScreen {
            get {
                if (this._UserLoginScreen == null) {
                    this._UserLoginScreen = this.CreateViewModel<UserLoginScreenViewModel>( "UserLoginScreen");
                }
                return _UserLoginScreen;
            }
        }
        
        [uFrame.IOC.InjectAttribute()]
        public virtual UserLoginScreenController UserLoginScreenController {
            get {
                if (_UserLoginScreenController==null) {
                    _UserLoginScreenController = Container.CreateInstance(typeof(UserLoginScreenController)) as UserLoginScreenController;;
                }
                return _UserLoginScreenController;
            }
            set {
                _UserLoginScreenController = value;
            }
        }
        
        public override void Load() {
            Container.RegisterViewModelManager<UserLoginScreenViewModel>(new ViewModelManager<UserLoginScreenViewModel>());
            Container.RegisterController<UserLoginScreenController>(UserLoginScreenController);
            Container.RegisterViewModel<UserLoginScreenViewModel>(UserLoginScreen, "UserLoginScreen");
        }
    }
}
